{% set name = "msg-extractor" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/extract-msg/extract_msg-{{ version }}.tar.gz
  sha256: 7f80701200192effc18b394fb31cdc1fb39bf5de7b909c1b8e106a2796c407ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - imapclient
    - olefile
    - pip
    - python
    - tzlocal
  run:
    - imapclient
    - olefile
    - python
    - tzlocal
    - compressed-rtf

test:
  imports:
    - extract_msg

about:
  home: https://github.com/mattgwwalker/msg-extractor
  license: GPL 3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Extracts emails and attachments saved in Microsoft Outlook's .msg files
  dev_url: https://github.com/mattgwwalker/msg-extractor

extra:
  recipe-maintainers:
    - agcopenhaver
    - pmlandwehr
    - rluria14
    - oblute
