{% set name = "msg-extractor" %}
{% set version = "0.23.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/e/extract-msg/extract_msg-{{ version }}.tar.gz"
  sha256: "3746d5f68266740575ef9097516f39c5f601fa031e188cea338a13b66de16ada"

build:
  skip: True  # [win and py>35]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - imapclient
    - olefile
    - pip
    - python
    - tzlocal
  run:
    - imapclient
    - olefile
    - python
    - tzlocal

test:
  imports:
    - extract_msg

about:
  home: https://github.com/mattgwwalker/msg-extractor
  license: GPL 3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Extracts emails and attachments saved in Microsoft Outlook's .msg files"
  dev_url: https://github.com/mattgwwalker/msg-extractor

extra:
  recipe-maintainers:
    - agcopenhaver
    - pmlandwehr
