{% set name = "msg-extractor" %}
{% set version = "0.23.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/e/extract-msg/extract_msg-{{ version }}.tar.gz"
  sha256: "b83c1931821daa900e72757e1627f1b0d2967a2cd863ff7ad9f3d5013681f937"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - imapclient
    - olefile
    - pip
    - python
    - tzlocal
  run:
    - imapclient
    - olefile
    - python
    - tzlocal

test:
  imports:
    - extract_msg

about:
  home: https://github.com/mattgwwalker/msg-extractor
  license: GPL 3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Extracts emails and attachments saved in Microsoft Outlook's .msg files"
  dev_url: https://github.com/mattgwwalker/msg-extractor

extra:
  recipe-maintainers:
    - agcopenhaver
    - pmlandwehr
