{% set name = "msg-extractor" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/extract-msg/extract_msg-{{ version }}.tar.gz
  sha256: ae6ce5f78fddb582350cb49bbf2776eadecdbf3c74b7a305dced42bd187a5401

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imapclient
    - olefile
    - python >=3.6
    - tzlocal
    - ebcdic
    - compressed-rtf

test:
  imports:
    - extract_msg

about:
  home: https://github.com/mattgwwalker/msg-extractor
  license: GPL 3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Extracts emails and attachments saved in Microsoft Outlook's .msg files
  dev_url: https://github.com/mattgwwalker/msg-extractor

extra:
  recipe-maintainers:
    - mxr-conda
    - agcopenhaver
    - rluria14
    - oblute
    - jan-janssen
