travis:
  secure:
    BINSTAR_TOKEN: QWwJ3d8M1TLcjOT8P2IAH0xZBIlBDWUqZd8kuWmW+bp2Ccr+FIiMlFdRM4QcNZ7kpp7T6Xsi3GFsEMj3BCz4SJEEH5o4NrZu+EtZs211zRbIsEkDtJP7wqLqHf1UomoUVrYE+AcmKAqDy5MXhMzk2F1JjeBcI91MRAXIXCMGH8XmdhoxPGSNY8PM2FFqILZ58tmZKkGGIGBegbA4GUJqt92rjJrVox2Cy8ZgWPDzvfoYvgWe0m2NwTLhutmvIjoGwuqsCBTAw0HaBHji6Vm8sn0o9jGmkg7qhOfDv807hPs2m1ftIOtmCBPEVZ34MRoJ7bEPWMKAHyjWEi55hhwt/RJ9JcfxoGDm1uT90cm7FWtCnMFdl1zXJgrLDpkvkWshYphzDfPTkjVzRheVkj89QpUdp1eywU9dh6a5haA3A5xmo8+8s+TQZWJ4hzpKK8PktvOtFckVGmaf794Z3JE9GBrVF/aATyqZvEs8fcOIVITMAVRWiRIZY7QCZTj0eX9b7sjQIweqmQLiMSEXRwiq/qZ8dJ8FsVd7lHC32lwyqsq3xV108NElvmx6kB+Ct0KYIbUj1QPZJUtp4e53JyCzwWHsalQdVX1Amp2G5HIWxduPO9rxJmMTICAJD52z0Kq6HnOcp/6fVmkY+m/RorvWLflylkn6AIhWMZDZJ7Sk/Uo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
